language: node_js
node_js: 
  - "6"
env:
  - CXX=g++-4.8
  - PORT=3000
  - MONGODB_URI=mongodb://localhost/discog
  - APP_SECRET=app-secret
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - mongodb-3.2-precise

    packages:
      - g++-4.8
      - mongodb-org-server